// react/src/components/TodoList.tsx
import { DateTime } from "luxon";
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { v4 as uuid } from "uuid";
import {
  addTodo,
  fetchTodos,
  todosIsLoadingSelector,
  todosSelector,
} from "../store/todoSlice";
import TodoListItem from "./TodoListItem";

const TodoList = () => {
  const dispatch = useDispatch();
  const isLoading = useSelector(todosIsLoadingSelector);
  const todos = useSelector(todosSelector);
  const [newTodoContent, setNewTodoContent] = useState("");

  useEffect(() => {
    dispatch(fetchTodos());
  }, [dispatch]);

  const onAddTodo = () => {
    if (newTodoContent) {
      const newTodo = {
        id: uuid(),
        content: newTodoContent,
        isDone: false,
        created: DateTime.now(),
      };
      dispatch(addTodo(newTodo));
      setNewTodoContent("");
    }
  };

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <section>
      <div className="todo--input">
        <input
          name="New todo"
          value={newTodoContent}
          onChange={(e) => setNewTodoContent(e.target.value)}
        />
        <button onClick={onAddTodo}>Add todo</button>
      </div>
      {todos.length ? (
        <ul>
          {todos.map((todo) => (
            <TodoListItem key={todo.id} todo={todo} />
          ))}
        </ul>
      ) : (
        <div>No todos</div>
      )}
    </section>
  );
};

export default TodoList;

// vue/src/components/TodoList.vue
<template>
	<div class="container">
		<div class="todo">
			<div class="todo--input">
				<input v-model="todoContent" type="text" name="New todo" />
				<button @click="addTodoItem">Add todo</button>
			</div>
			<div v-if="todos.length > 0" class="todo--todos">
				<todo-list-item
					v-for="(todoItem, index) in todos"
					:todoItem="todoItem"
					:key="index"
				/>
			</div>
			<div v-else>
				<h3>No todos</h3>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
import { DateTime } from "luxon";
import { defineComponent } from "vue";
import { MutationTypes, store } from "@/store";
import { TodoItem } from "@/models/TodoItem";
import TodoListItem from "@/components/TodoListItem.vue";

export default defineComponent({
	components: {
		TodoListItem,
	},
	data() {
		return {
			todos: store.state.currentTodos,
			todoContent: "",
		};
	},
	methods: {
		addTodo() {
			store.dispatch(MutationTypes.ADD_TODO, {
				content: this.todoContent,
				isDone: false,
				created: DateTime.now(),
			} as TodoItem);
		},
	},
});
</script>
<style lang="stylus">
.container {
	display: grid;
	place-content: center;
	height: 50vh;
	width: 100vw;
}

.todo {
	&--input {
		display: flex;
		flex-direction: row;
		justify-content: space-between;
	}
}
</style>
